export const GET_INTEREST = 'GET_INTEREST';
export const ADD_INTEREST = 'ADD_INTEREST';
export const INTEREST_ERROR = 'INTEREST_ERROR';
export const UPDATE_INTEREST = 'UPDATE_INTEREST';
export const DELETE_INTEREST = 'DELETE_INTEREST';