export const GET_EDUCATION = 'GET_EDUCATION';
export const ADD_EDUCATION = 'ADD_EDUCATION';
export const EDUCATION_ERROR = 'EDUCATION_ERROR';
export const UPDATE_EDUCATION = 'UPDATE_EDUCATION';
export const DELETE_EDUCATIOIN = 'DELETE_EDUCATIOIN';