export const GET_EXPERINCE = 'GET_EXPERINCE';
export const ADD_EXPERINCE = 'ADD_EXPERINCE';
export const EXPERINCE_ERROR = 'EXPERINCE_ERROR';
export const UPDATE_EXPERIENCE = 'UPDATE_EXPERIENCE';
export const DELETE_EXPERIENCE = 'DELETE_EXPERIENCE';